### PR TITLE
[News] Manx release

### PR DESCRIPTION
**Pull request by ybiquitous**
This change adds news about the new feature: **analyzing branches**

### CODE REVIEW

**Review by yykamei — APPROVED** [review]
LGTM

**Review by dev-yakuza — APPROVED** [review]
LGTM 👍 

Just a simple question. Don't we need to show the limitation of the issues? Will it be on another document?

**Comment by ybiquitous** [comment]
We don't have such a limitation now.

**Comment by dev-yakuza** [comment]
Sorry, I confused with the PR limitation.

Thanks!

**Pull request merged**
