### PR TITLE
Enterprise release — January 2021

### PR DESCRIPTION
**Pull request by yykamei**

### CODE REVIEW

**Comment by yykamei** [comment]
@ybiquitous Are there any other notable changes regarding Sider Enterprise?

**Comment by ybiquitous** [comment]
GitHub access token passed to Runners?

**Comment by yykamei** [comment]
Thank you. I added 2bb71d9

**Comment by ybiquitous** [comment]
Is it needed to write also weaker token (read)?

**Comment by yykamei** [comment]
How about this e4059e0

**Review by ybiquitous — APPROVED** [review]
LGTM 👍

**Comment by yykamei** [comment]
Thank you

**Pull request merged**
