### PR TITLE
Bump dependencies via `yarn upgrade`

### PR DESCRIPTION
**Pull request by ybiquitous**

### CODE REVIEW

**Comment by ybiquitous** [comment]
It looks like no problem on the [Netlify preview site](https://deploy-preview-131--sider-docs.netlify.com/). 👍

**Comment by akito19** [comment]
How about upgrading `/website/yarn.lock` as well?

**Comment by ybiquitous** [comment]
Oh, I forgot it. 😅 

`/website/yarn.lock` has `docusaurus`, which is the main runtime package, so I think better to try update on another PR. How about?

image

**Comment by akito19** [comment]
As you like. If there is no problem, upgrade `/website/yarn.lock` on this PR.
Definitely, upgrading it on another PR is safer than on this PR.

**Comment by ybiquitous** [comment]
Sure, I pushed the Docusaurus update. 👍 

- https://github.com/facebook/Docusaurus/blob/v1.7.3/CHANGELOG.md
- https://github.com/facebook/Docusaurus/compare/v1.7.1...v1.7.3

**Pull request merged**
