### PR TITLE
Remove TSLint link from Custom Analysis Configuration documentation page

### PR DESCRIPTION
**Pull request by radomirbosak**
Fixes: #692

### CODE REVIEW

**Comment by radomirbosak** [comment]
Looks like this change created broken links to `/tools/javascript/tslint`

**Comment by ybiquitous** [comment]
I think it is valuable to keep even the old tools like [golint](https://github.com/sider/sider-docs/blob/84da6be1a666053c8deaba4ca2ef1c43c1211c28/docs/tools/go/golint.md).

**Review by ybiquitous — APPROVED** [review]
Good catch! 👍🏼

**Comment by radomirbosak** [comment]
> I think it is valuable to keep even the old tools like golint.

I'm not opposing this, just curious what's the value in keeping the document. I guess we want to avoid breaking links in our changelogs. Is there anything else?

**Comment by radomirbosak** [comment]
In any case, I restored the documentation page and removed just the lint to it in the docs (Custom Analyzer Configuration page). I hope it's ok like this.

**Comment by ybiquitous** [comment]
> I'm not opposing this, just curious what's the value in keeping the document. I guess we want to avoid breaking links in our changelogs. Is there anything else?

If users have a link to a removed tool, I don't think it is useful the link would be broken.
For breaking links, remark-lint could detect them.

**Pull request merged**
