### PR TITLE
Drop the support of Python 2

### PR DESCRIPTION
**Pull request by yykamei**
Following https://github.com/sider/devon_rex/pull/307 and https://github.com/sider/runners/pull/1579, I want to update the documentation.

Note I kept the version of Flake8 and PyLint deliberately. If I should update these versions, please comment here.

### CODE REVIEW

**Comment by yykamei** [comment]
Python is already bumped to 3.9.0. Should I update this PR?

**Comment by suetsuguk** [comment]
In my [PR](https://github.com/sider/sider-docs/pull/517/files), I have already updated the version to 3.9.0.

**Comment by yykamei** [comment]
OK, I've updated this PR to just drop the support of Python 2.

**Review by suetsuguk — APPROVED** [review]
👍

**Review by ybiquitous — APPROVED** [review]
👍

**Comment by yykamei** [comment]
@suetsuguk Would you merge this PR along with your PR? Perhaps, it should be merged at the same time.

**Comment by suetsuguk** [comment]
That would be good. I take this PR.

**Pull request merged**
